set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'ycm-core/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" basic settings
set mouse=a
syntax on
" disable highlighting after search by enter key
nnoremap <silent> <CR> :nohlsearch<CR><CR>
set ignorecase
set smartcase
set number relativenumber

" tab settings
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

" set cursorline
" set cursorcolumn
" set wildmode=longest,list,full

" TODO auto-fill parenthesis
inoremap { {}<ESC>ha

" TODO change leader key
" let mapleader=" "

" trim trailing spaces
autocmd BufWritePre * %s/\s\+$//e

" use system clipboard
set clipboard+=unnamed

" TODO toggle comment
" TODO nerd-tree / file explore


" TODO status bar settings

" YCM settings
"let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion= 1
